// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUser(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	ListUser(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
